<?php
session_start();

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    // Save the order details and public key in the session
    $_SESSION['orderDetails'] = $_POST['orderDetails'];
    $_SESSION['publicKey'] = $_POST['publicKey'];

    // Display a form for uploading the private key
    echo "<h2>Complete Your Payment</h2>";
    echo "<form action='sign_transaction.php' method='post' enctype='multipart/form-data'>";
    echo "<input type='hidden' name='orderDetails' value='" . htmlspecialchars($_SESSION['orderDetails']) . "'>";
    echo "<input type='hidden' name='publicKey' value='" . htmlspecialchars($_SESSION['publicKey']) . "'>";
    echo "<label for='privateKeyFile'>Upload your private key file:</label><br>";
    echo "<input type='file' id='privateKeyFile' name='privateKeyFile' required><br><br>";
    echo "<button type='submit' class='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded'>Sign and Complete Payment</button>";
    echo "</form>";
} else {
    // Redirect back to cart if this page is accessed without submitting the cart form
    header('Location: cart.php');
    exit();
}
?>

<!DOCTYPE html>
<html>
<head>
    <title>Complete Payment</title>
    <!-- Additional head elements (like CSS) here -->
</head>
<body>
    <!-- The content generated by PHP will be displayed here -->
</body>
</html>
