<?php
session_start();

function calculateTotalAmount($orderDetails) {
    $orderDetailsArray = json_decode($orderDetails, true);
    $totalAmount = 0;
    foreach ($orderDetailsArray as $item) {
        $totalAmount += $item['quantity'] * $item['price'];
    }
    return $totalAmount;
}

if ($_SERVER["REQUEST_METHOD"] == "POST" && isset($_FILES['privateKeyFile'])) {
    $flaskSignUrl = 'http://127.0.0.1:5002/sign';
    $flaskAddTransactionUrl = 'http://127.0.0.1:5002/create_transaction';

    $orderDetails = $_SESSION['orderDetails'] ?? '';
    $publicKey = $_SESSION['publicKey'] ?? '';

    if ($_FILES['privateKeyFile']['error'] === UPLOAD_ERR_OK) {
        $filePath = $_FILES['privateKeyFile']['tmp_name'];
        $cFile = curl_file_create($filePath);

        $signData = [
            'orderDetails' => $orderDetails,
            'privateKeyFile' => $cFile
        ];

        $ch = curl_init($flaskSignUrl);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $signData);
        $signResponse = curl_exec($ch);
        $signData = json_decode($signResponse, true);
        curl_close($ch);

        echo $signData;
        
        if ($signData && $signData['success']) {
            $blockchainData = json_encode([
                'order_details' => $orderDetails,
                'sender_public_key' => $publicKey,
                'signature' => $signData['signature'],
                'amount' => calculateTotalAmount($orderDetails),
                'transaction_details' => $orderDetails 
            ]);

            $ch = curl_init($flaskAddTransactionUrl);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_POST, true);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $blockchainData);
            curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
            $blockchainResponse = curl_exec($ch);
            $blockchainData = json_decode($blockchainResponse, true);
            curl_close($ch);

            if ($blockchainData && $blockchainData['status'] == 'success') {
                echo "Transaction added to blockchain successfully.";
            } else {
                echo "Transaction failed: " . $blockchainData['message'];
            }
        } else {
            echo "Failed to sign the transaction. Error: " . ($signData['message'] ?? 'Unknown error');
        }
    } else {
        echo "Error in uploading the private key file.";
    }
} else {
    echo "No private key file received. Please try again.";
}

session_destroy();
?>

<!DOCTYPE html>
<html>
<head>
    <title>Transaction Status</title>
    <!-- Additional head elements (like CSS) here -->
</head>
<body>
    <!-- The content generated by PHP will be displayed here -->
</body>
</html>
